In [13]:
# Import stuff
import numpy as np
import pandas as pd

In [20]:
# Get random Sudoku 
sudoku_data = pd.read_csv('/home/stijn/Projects/sudoku_solvers/1000_sudokus.csv')
all_puzzles = sudoku_data['quizzes']
# random_sudoku_index = np.random.randint(all_puzzles.shape[0])
random_sudoku_index = 42
random_sudoku = all_puzzles[random_sudoku_index]
random_sudoku_solution = sudoku_data['solutions'][random_sudoku_index]


In [19]:
# Create datastructure for sudoku
def make_array_from_string(sudoku):
    return np.array(list(sudoku), dtype=int).reshape((9,9))

sudoku = make_array_from_string(random_sudoku)
solution = make_array_from_string(random_sudoku_solution)
print(solution)

[[1 2 3 8 9 7 5 4 6]
 [9 5 6 4 1 3 8 7 2]
 [8 4 7 2 6 5 1 9 3]
 [6 9 1 3 7 8 2 5 4]
 [5 8 4 9 2 1 3 6 7]
 [7 3 2 5 4 6 9 1 8]
 [2 1 9 6 3 4 7 8 5]
 [3 6 8 7 5 9 4 2 1]
 [4 7 5 1 8 2 6 3 9]]


In [10]:
# Pretty print function
def print_sudoku(sudoku):
    print(19*"-")
    for row in range(9):
        print('|', end='')
        for column in range(9):
            print(sudoku[row, column], end='')
            if (column+1)%3 == 0: 
                print('|', end='')
            else:
                print(' ', end='')
        print()
        if (row) % 3 == 2:
            print(19*"-")

In [11]:
test_values = np.arange(1, 10)
def backtrack_solve_sudoku(sudoku, n):
    # This is solved
    if n == 9*9:
        # print(np.all(sudoku == solution))
        # print_sudoku(sudoku)
        return
    
    # Get row, column, and block
    row, column = n//9, n%9
    block_firstrow = 3*(row//3)
    block_firstcolumn = 3*(column//3)
    
    # If the entry is available
    if sudoku[row, column] == 0:
        
        # Get list of available values
        unavailable_row_values = np.unique(sudoku[row])
        unavailable_column_values = np.unique(sudoku[:,column])
        unavailable_block_values = np.unique(sudoku[block_firstrow:block_firstrow+3, block_firstcolumn:block_firstcolumn+3])
        unavailable_values = np.union1d(unavailable_row_values, np.union1d(unavailable_column_values, unavailable_block_values))
        available_values = np.setdiff1d(test_values, unavailable_values)
        
        for candidate in available_values:
            sudoku[row, column] = candidate
            backtrack_solve_sudoku(sudoku, n+1)
            sudoku[row, column] = 0
        
    else:
        # Skip this entry
        backtrack_solve_sudoku(sudoku, n+1)
    

def solve_sudoku(sudoku):
    backtrack_solve_sudoku(sudoku,0)

In [21]:
import timeit
number_of_repeats = 1000
total_time = timeit.timeit(lambda: solve_sudoku(sudoku), number= 1000)
single_time = total_time/number_of_repeats

In [22]:
print(single_time)

0.011027520075998836
